name = input('What is your name?')
print('Your name is ' + name)
age = int(input('What is your age?'))
print('You are ' + str(age) + ' years old.')
year = str((2018 - age) + 100)
print('You will be 100 in ' + year)
